version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ecommerce-network

  inventory-db:
    image: postgres:17-alpine
    container_name: inventory-db
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB= inventoryDB
    networks:
      - ecommerce-network
    volumes:
      - inventory-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:17-alpine
    container_name: order-db
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB= orderDB
    networks:
      - ecommerce-network
    volumes:
      - order-db-data:/var/lib/postgresql/data

  discovery-service:
    image: joelcr7/discovery-service
    container_name: discovery-service
    networks:
      - ecommerce-network

  config-server:
    image: joelcr7/config-server
    container_name: config-server
    networks:
      - ecommerce-network
    depends_on:
      discovery-service:
        condition: service_started

  inventory-service:
    image: joelcr7/inventory-service
    container_name: inventory-service
    networks:
      - ecommerce-network
    depends_on:
      - config-server
      - zipkin
      - inventory-db

  order-service:
    image: joelcr7/order-service
    container_name: order-service
    networks:
      - ecommerce-network
    depends_on:
      - config-server
      - zipkin
      - order-db

  api-gateway:
    image: joelcr7/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    depends_on:
      - order-service
      - inventory-service

volumes:
  inventory-db-data:
  order-db-data:

networks:
  ecommerce-network: