apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: joelcr7/ecommerce-inventory-service
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_SERVICE
            valueFrom:                # get value from config map (note we can also pass the value directly here using value:)
              configMapKeyRef:
                name: my-config
                key: INVENTORY_DB_SERVICE
          - name: DB_NAME
            value: inventoryDB
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: INVENTORY_DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: INVENTORY_DB_PASSWORD
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 9010

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
  - port: 80        # this service will listen for requests on port 80
    targetPort: 9010    # the requests will then be transferred to the pod on port 9020 (mentioned above)

