apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: joelcr7/ecommerce-order-service
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_SERVICE
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: ORDER_DB_SERVICE
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: ORDER_DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: ORDER_DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: ORDER_DB_PASSWORD
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 9020

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 80        # this service will listen for requests on port 80
    targetPort: 9020    # the requests will then be transferred to the pod on port 9020 (mentioned above)

