apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque              # this means passing simple key-value pair, there are may types, like tls certificates ,etc
data:
  INVENTORY_DB_USER: cG9zdGdyZXM=        # here we need to pass base64 encoded value of the actual string (do it through online tool)
  INVENTORY_DB_PASSWORD: cG9zdGdyZXM=
  INVENTORY_DB_NAME: aW52ZW50b3J5REI=
  ORDER_DB_USER: cG9zdGdyZXM=
  ORDER_DB_PASSWORD: cG9zdGdyZXM=
  ORDER_DB_NAME: b3JkZXJEQg==